- firewalld:
    service: https
    permanent: true
    state: enabled
- firewalld:
    port: '{{ http_port }}/tcp'
    permanent: true
    state: disabled
- firewalld:
    port: '{{ snmp_port }}/udp'
    permanent: true
    state: disabled
- firewalld:
    port: '{{ inter_ip_range }}/24'
    zone: internal
    state: enabled